In [1]:
import os
from utils.preprocessor import DataPreprocessor

current_dir = os.getcwd()
print("Current directory:", current_dir)

Current directory: c:\Users\marco\Documents\ITAM\Thesis\Code\notebooks


In [8]:
file_path = os.path.join(
    "..", "datasets", "preprocessed", "movielens", "p_movielens_100k.csv"
)
preprocessor = DataPreprocessor(file_path)
preprocessor.load_data()
preprocessor.calculate_unique_counts()
save_dir = os.path.join(
    "..", "datasets", "preprocessed", "movielens", "p_movielens_100k_norm_adj_mat"
)

In [1]:
import os
from utils.datahandler import DataHandler

In [2]:
datahandler = DataHandler(
    dataset_path=os.path.join(
        "..", "datasets", "preprocessed", "movielens", "p_movielens_100k.csv"
    ),
    test_split=0.2,
    batch_size=5,
)

In [3]:
train, test = datahandler.get_train_test_datasets()

In [4]:
datahandler.dataset_size

99693

In [6]:
datahandler.test_size + datahandler.train_size

99693

In [7]:
datahandler.train

15951

In [10]:
sum(1 for i in dataset)

99693

In [9]:
dataset = datahandler.load_data()

In [10]:
dataset.cardinality()

<tf.Tensor: shape=(), dtype=int64, numpy=-2>

In [7]:
for t in test.take(1):
    print(t)

({'user_index': <tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[813],
       [795],
       [715],
       [695],
       [822]])>, 'item_index': <tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[ 498],
       [1398],
       [ 441],
       [ 411],
       [ 245]])>}, <tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[4.],
       [5.],
       [5.],
       [4.],
       [3.]], dtype=float32)>)


In [2]:
from models.ngcf4 import NGCFModel
import tensorflow as tf

In [12]:
preprocessor.num_users, preprocessor.num_items

(943, 1664)

In [7]:
save_dir = os.path.join(
    "..", "datasets", "preprocessed", "movielens", "p_movielens_100k_norm_adj_mat"
)
model = NGCFModel(
    num_users=preprocessor.num_users,
    num_items=preprocessor.num_items,
    num_layers=2,
    embedding_size=32,
    n_fold=1,
    adj_save_dir=save_dir,
)

In [8]:
# Compile the model
model.compile(
    optimizer="adam",  # Adjust the optimizer and learning rate as needed
    loss="mean_squared_error",  # You can also use a custom loss function here
    metrics=[
        tf.keras.metrics.RootMeanSquaredError()
    ],  # Add any additional metrics you want to track
)

In [9]:
history = model.fit(train, epochs=5, validation_data=test, verbose=1)

Epoch 1/5


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: annotated name 'embeddings_updated' can't be nonlocal (__autograph_generated_fileis90gb3j.py, line 20)
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: annotated name 'embeddings_updated' can't be nonlocal (__autograph_generated_fileis90gb3j.py, line 20)
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
(2607, 2607) (0,)


ValueError: in user code:

    File "c:\Users\marco\miniconda3\envs\rs-thesis\lib\site-packages\keras\engine\training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\marco\miniconda3\envs\rs-thesis\lib\site-packages\keras\engine\training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\marco\miniconda3\envs\rs-thesis\lib\site-packages\keras\engine\training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\marco\miniconda3\envs\rs-thesis\lib\site-packages\keras\engine\training.py", line 993, in train_step
        y_pred = self(x, training=True)
    File "c:\Users\marco\miniconda3\envs\rs-thesis\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\marco\AppData\Local\Temp\__autograph_generated_file6w3kq1gl.py", line 11, in tf__call
        (final_u_embeddings, final_i_embeddings) = ag__.converted_call(ag__.ld(self).compute_final_embeddings, (ag__.ld(user_indices), ag__.ld(item_indices)), None, fscope)
    File "C:\Users\marco\AppData\Local\Temp\__autograph_generated_fileyx5txio5.py", line 48, in tf__compute_final_embeddings
        ag__.for_stmt(ag__.ld(self).ngcf_layers, None, loop_body_1, get_state_1, set_state_1, ('concat_embeddings',), {'iterate_names': 'layer'})
    File "C:\Users\marco\AppData\Local\Temp\__autograph_generated_fileyx5txio5.py", line 40, in loop_body_1
        ag__.for_stmt(ag__.converted_call(ag__.ld(range), (ag__.ld(self).n_fold,), None, fscope), None, loop_body, get_state, set_state, ('layer_embeddings',), {'iterate_names': 'i_fold'})
    File "C:\Users\marco\AppData\Local\Temp\__autograph_generated_fileyx5txio5.py", line 39, in loop_body
        layer_embeddings += ag__.converted_call(layer, (concat_embeddings, adj_submatrix), None, fscope)
    File "c:\users\marco\documents\itam\thesis\code\models\ngcf4.py", line 36, in call
        relevant_embeddings: tf.Tensor = tf.sparse.sparse_dense_matmul(

    ValueError: Exception encountered when calling layer "ngcf_model" "                 f"(type NGCFModel).
    
    in user code:
    
        File "c:\users\marco\documents\itam\thesis\code\models\ngcf4.py", line 95, in call  *
            final_u_embeddings, final_i_embeddings = self.compute_final_embeddings(
        File "c:\users\marco\documents\itam\thesis\code\models\ngcf4.py", line 122, in compute_final_embeddings  *
            layer_embeddings += layer(concat_embeddings, adj_submatrix)
        File "c:\Users\marco\miniconda3\envs\rs-thesis\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler  **
            raise e.with_traceback(filtered_tb) from None
        File "c:\users\marco\documents\itam\thesis\code\models\ngcf4.py", line 36, in call
            relevant_embeddings: tf.Tensor = tf.sparse.sparse_dense_matmul(
    
        ValueError: Exception encountered when calling layer "ngcf_layer" "                 f"(type NGCFLayer).
        
        Shape must be rank 2 but is rank 1 for '{{node ngcf_model/ngcf_layer/SparseTensorDenseMatMul/SparseTensorDenseMatMul}} = SparseTensorDenseMatMul[T=DT_FLOAT, Tindices=DT_INT64, adjoint_a=false, adjoint_b=false](ngcf_model/SparseTensor/indices, ngcf_model/Cast, ngcf_model/SparseTensor/dense_shape, ngcf_model/concat)' with input shapes: [199386,2], [199386], [2], [0].
        
        Call arguments received by layer "ngcf_layer" "                 f"(type NGCFLayer):
          • embeddings=tf.Tensor(shape=(0,), dtype=float32)
          • adj_submatrix=<tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x000001E88AACC9D0>
          • self_messages=False
    
    
    Call arguments received by layer "ngcf_model" "                 f"(type NGCFModel):
      • inputs=('tf.Tensor(shape=(None, None), dtype=int32)', 'tf.Tensor(shape=(None, None), dtype=int32)')


In [ ]:
for t in train.take(1):
    print(t)

((<tf.Tensor: shape=(8192, 1), dtype=int32, numpy=
array([[464],
       [207],
       [274],
       ...,
       [607],
       [ 96],
       [404]])>, <tf.Tensor: shape=(8192, 1), dtype=int32, numpy=
array([[ 908],
       [ 554],
       [1395],
       ...,
       [1206],
       [ 661],
       [ 778]])>), <tf.Tensor: shape=(8192, 1), dtype=float32, numpy=
array([[3.],
       [3.],
       [3.],
       ...,
       [1.],
       [5.],
       [1.]], dtype=float32)>)


In [3]:
embedding = tf.keras.layers.Embedding(
    input_dim=3,
    output_dim=5,
    embeddings_initializer="glorot_uniform",
    name="user_embeddings",
)

In [6]:
embedding(tf.constant([1, 2, 1], dtype=tf.int64))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[-0.07547277, -0.31001997, -0.07312572,  0.70299417,  0.0081802 ],
       [-0.06452125,  0.3566932 ,  0.32417625, -0.7915747 ,  0.06304514],
       [-0.07547277, -0.31001997, -0.07312572,  0.70299417,  0.0081802 ]],
      dtype=float32)>

In [13]:
import tensorflow as tf

# Assuming tensor1 has shape (3, 4) and tensor2 has shape (5, 4)
tensor1 = tf.random.normal((3, 4))
tensor2 = tf.random.normal((5, 4))

# Combine the tensors vertically to get a tensor of shape (8, 4)
combined_tensor = tf.concat([tensor1, tensor2], axis=0)

In [14]:
combined_tensor

<tf.Tensor: shape=(8, 4), dtype=float32, numpy=
array([[ 0.48940158,  2.383477  , -1.0404491 , -0.54409355],
       [ 1.0170258 , -0.17847705,  0.9201864 , -0.7359506 ],
       [ 1.240829  , -0.10877343, -0.48835427, -0.9066484 ],
       [-0.43524253,  1.4310521 ,  0.15435778,  1.3330446 ],
       [-1.7806327 ,  0.08148877, -0.00600956, -0.25840324],
       [-1.3189485 ,  0.97985804, -0.5623187 , -0.9498832 ],
       [ 0.5326377 , -0.41229564, -0.8957077 , -1.236353  ],
       [ 2.4029365 , -0.9349132 ,  1.8310658 ,  0.9607314 ]],
      dtype=float32)>